### ISSUE TITLE
Failed to load database information

### ISSUE THREAD

**Issue by KimBaRog** [rainforestnet/CrystalReportsNinja#13]
The report is using database type of File System Data with a starting directory that I can read access.
C:\CrystalReports>crystalreportsninja.exe -F c:\CrystalReports\CountCMS-DbutilFiles.rpt
Report loaded successfully
Database Login done
Error in File CountCMS-DbutilFiles 7652_7088_{4E8BCBC7-C766-44FD-AB1C-9467871663CC}.rpt:
Failed to load database information.
Error in File CountCMS-DbutilFiles 7652_7088_{4E8BCBC7-C766-44FD-AB1C-9467871663CC}.rpt:d database information.
Failed to load database information.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)

Any help would be appreciated.

**Comment by ancelP** [comment]
almost got the same problem here.  can someone help.?

27-03-2018	16:02:13	Report loaded successfully
27-03-2018	16:02:13	Output Filename : test2.pdf
27-03-2018	16:02:13	Output format : pdf
27-03-2018	16:02:14	Discrete Parameter : PV_FOR_DATE = 2018-03-26
27-03-2018	16:02:16	Exception: Error in File 0151 22444_12724_{8A3B3C0E-029C-48E8-9949-6EAD2B25DCD9}.rpt:
Failed to load database information.
27-03-2018	16:02:16	Inner Exception: System.Runtime.InteropServices.COMException (0x800002CD): Error in File 0151 22444_12724_{8A3B3C0E-029C-48E8-9949-6EAD2B25DCD9}.rpt:
Failed to load database information.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)

**Comment by jschneck1** [comment]
Same here:

04-05-2018	16:08:23	Report loaded successfully
04-05-2018	16:08:23	Output Filename : C:\cr_ninja\dq_report.xls
04-05-2018	16:08:23	Output format : xls
04-05-2018	16:08:26	Exception: Failed to load database information. Error in File dq_report_indirect_weekly 7228_15120_{148D32F4-9003-47D8-BEE3-CB55EBA70273}.rpt: Failed to load database information.
04-05-2018	16:08:26	Inner Exception: System.Runtime.InteropServices.COMException (0x800002CD): Failed to load database information.
Error in File dq_report_indirect_weekly 7228_15120_{148D32F4-9003-47D8-BEE3-CB55EBA70273}.rpt:
Failed to load database information.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)

**Comment by KatSamson-dev** [comment]
Was there a resolution for this item?
