### ISSUE TITLE
Unable to load report.

### ISSUE THREAD

**Issue by ascii0rez** [rainforestnet/CrystalReportsNinja#39]
Hello friends. Could you please help me? as I already bang my head on the wall :)

I am using win10, 64bit with the newest "3500" assemlbies installed.
Regardless of the report I try to open (and I checked their validity), I always get:

Exception: Load report failed.
Inner Exception: System.Runtime.InteropServices.COMException (0x8000020D): Unable to load report.
   at CrystalDecisions.ReportAppServer.ClientDoc.ReportClientDocumentClass.Open(Object& DocumentPath, Int32 Options)
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.Open(Object& DocumentPath, Int32 Options)
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.EnsureDocumentIsOpened()

I have read in other forums that this might be a permission issue, but I run as administrator and even so add "Everyone/Full Control" to the folder and its contents.

What can be the issue???

Thanks in advance!

**Comment by fogoat** [comment]
Can you copy and paste the file elsewhere and try to run the copied report? 

Is the report already opened or corrupt? 

Can you open from Crystal reports desktop client?

**Comment by ascii0rez** [comment]
Hi there sunk818,

Thank you! I really appreciate the care you took to write to me.
Apparently, the reports were created by a 3rd party designer called “i-net clear reports designer”, and that was the problem.
I have not used the desktop version of Crystal Reports, but I created a report using the official VS SAP plug-in and it worked 😊
Are you familiar with cross compatibility issues?

Thanks a lot!
