### ISSUE TITLE
CrystalReportsNinja.exe Database logon failed

### ISSUE THREAD

**Issue by itsoftsaeed** [rainforestnet/CrystalReportsNinja#63]
[25-08-2022](url)	16:58:04	Report loaded successfully
25-08-2022	16:58:04	Output Filename : test.pdf
25-08-2022	16:58:04	Output format : pdf
25-08-2022	16:58:04	Exception: Database logon failed.
25-08-2022	16:58:04	Inner Exception: System.Runtime.InteropServices.COMException (0x8004100F): Database logon failed.
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)

when I try to run with 32bit OS the report is working successfully, but try to run with 64Bit OS, the following error occurred Exception: Database logon failed...................., similarly I cannot deploy on remotely window server  2019 64Bit OS, same problem facing....
my parameters in Command Line are: 
D:\Web\xampp\htdocs\cr>CrystalReportsNinja -U"dw01_wit" -P"_khan&&bro" -F news.rpt -S"localhost" -D"dw01_wifaq" -O test.pdf -E pdf

OR

also try as given below
D:\Web\xampp\htdocs\cr>CrystalReportsNinja.exe -U dw01_wit -P password -F news.rpt -S localhost  -D dw01_wifaq -O test.pdf -E pdf

I try to connect with MYSQL database through ODBC 32bit drivers .......

When I try to run simple report without adding any table into the report ..... it connected successfully. 
parameters in Command Line are: 
CrystalReportsNinja -F r6.rpt -O test.pdf -E pdf
Report loaded successfully
Database Login done
Completed

![Screenshot_7](https://user-images.githubusercontent.com/11254651/186662197-ab3fde93-4e94-4902-bbb2-fff09ab57aac.jpg)
[ninja-20220825165802.log](https://github.com/rainforestnet/CrystalReportsNinja/files/9424527/ninja-20220825165802.log)

any one can help me, to solve this problem how connect with CrystalReportsNinja, with credentials parameters , adding tables into the report through MYSQL odbc deriver.. ?

**Comment by fogoat** [comment]
It is difficult to say without seeing more detail because all you've posted here is the 32-bit ODBC and all the drivers you posted are 32-bit. So, yes, all your connections (I assume) are 32-bit even though you don't show user DSN entry for dw01_wifaq. 

When you are on the 64-bit OS, I suggest you:

- install 64-bit run-time for CrystalReportsNinja, 
- add a 64-bit database driver to connect to the database. 
- on server, run CrystalReportNinja from command line to test

There are other ways to configure the server, but what I suggest is the easiest.

**Comment by itsoftsaeed** [comment]
> It is difficult to say without seeing more detail because all you've posted here is the 32-bit ODBC and all the drivers you posted are 32-bit. So, yes, all your connections (I assume) are 32-bit even though you don't show user DSN entry for dw01_wifaq.
> 
> When you are on the 64-bit OS, I suggest you:
> 
> * install 64-bit run-time for CrystalReportsNinja,
> * add a 64-bit database driver to connect to the database.
> * on server, run CrystalReportNinja from command line to test
> 
> There are other ways to configure the server, but what I suggest is the easiest.

thanks for reply @sunk818 , can u help me after connecting with my pc remotely, and check where is the problem, I also try with 64 bit but in vain

**Comment by itsoftsaeed** [comment]
> It is difficult to say without seeing more detail because all you've posted here is the 32-bit ODBC and all the drivers you posted are 32-bit. So, yes, all your connections (I assume) are 32-bit even though you don't show user DSN entry for dw01_wifaq.
> 
> When you are on the 64-bit OS, I suggest you:
> 
> * install 64-bit run-time for CrystalReportsNinja,
> * add a 64-bit database driver to connect to the database.
> * on server, run CrystalReportNinja from command line to test
> 
> There are other ways to configure the server, but what I suggest is the easiest.

thanks for reply @sunk818

**Comment by fogoat** [comment]
Does what I say help you or you are still without a resolution?
