### ISSUE TITLE
Raised exception

### ISSUE THREAD

**Issue by Hitamashi** [rainforestnet/CrystalReportsNinja#7]
Hello,

I cannot run my command:
> CrystalReportsNinja.exe -F LeaveNotification_FromSV.rpt -O result.pdf -E pdf

It always returns this exception.

```
Exception: Load report failed.
Inner Exception: System.Runtime.InteropServices.COMException (0x80041811): Unsupported Operation. A document processed by the JRC engine cannot be opened in the C++ stack.
   at CrystalDecisions.ReportAppServer.ClientDoc.ReportClientDocumentClass.Open(Object& DocumentPath, Int32 Options)
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.Open(Object& DocumentPath, Int32 Options)
   at CrystalDecisions.ReportAppServer.ReportClientDocumentWrapper.EnsureDocumentIsOpened()
```
I am sure that there is no process open the report. I also checked the permissions (read&write), run as administrator.

I have checked with other reports. The problem is the same.

Try passing a "hardcode" parameter in the source code but it still not work.

Could you please help me with this problem?

Thanks in advance

**Comment by mhertzfeld** [comment]
Do you have the correct Crystal Runtimes installed?  I think I've seen that error before when the runtimes I had installed were a lower version than what the app was compiled for.  I would uninstall the runtime(s) you have installed currently and get then get the latest from SAP.

**Comment by Hitamashi** [comment]
Thank you.
But I have tried both version 13.0.20 and 13.0.21 of the Crystal Runtimes. Nothing works for me.
For more info, I have tried the command on Windows 10 and Windows Server 2008 R2.

**Comment by mhertzfeld** [comment]
OK.  Pretty sure that's the error I've gotten before when the versions were mismatched.

Try my fork of the project to see if it works for you.  https://github.com/mhertzfeld/CrystalReportsNinja

Before you do though make sure to uninstall all crystal reports runtimes you have installed and reinstall 13.0.21.

**Comment by erpnedir** [comment]
Hi, I have the same error. I checked the version of CR runtime and it is 13.0.21.
Here is the output. Can you help me pls?
`
c:\Users\workflow\Downloads\CrystalReportsNinja-master\Deployment\64-bit>Crystal
ReportsNinja -S srv2014 -F C:\Raporlar\Crystal_Firma.rpt -O C:\Raporlar\test.pdf
 -E pdf
Report loaded successfully
Database Login done
Exception: Bağlantı açılamadı.
Crystal_Firma 7508_7288_{A4E47FA9-3A16-4608-B06F-00C0990129D1}.rpt
Ayrıntılar:  [Veritabanı Satıcı Kodu: 17 ]
Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): Bağla
ntı açılamadı.
Crystal_Firma 7508_7288_{A4E47FA9-3A16-4608-B06F-00C0990129D1}.rpt
Ayrıntılar:  [Veritabanı Satıcı Kodu: 17 ]
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(Expo
rtOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRe
questContext reqContext)
`

**Comment by ancelP** [comment]
hi, i encountered exception like this.
[ninja-20180327160210.log](https://github.com/rainforestnet/CrystalReportsNinja/files/1850958/ninja-20180327160210.log)
