### ISSUE TITLE
Can't connect to Sybase ASE DB

### ISSUE THREAD

**Issue by k00l3** [rainforestnet/CrystalReportsNinja#70]
Not sure if this works connecting to Sybase ASE BD at port 4100

Report loaded successfully
Database Login done
Exception: Failed to open the connection.
Failed to open the connection.
Report 14964_15648_{6ACBE26A-F58B-44F6-B709-1E9C1AC4646D}.rpt
Inner Exception: System.Runtime.InteropServices.COMException (0x800002F4): Failed to open the connection.
Failed to open the connection.
Report  14964_15648_{6ACBE26A-F58B-44F6-B709-1E9C1AC4646D}.rpt
   at CrystalDecisions.ReportAppServer.Controllers.ReportSourceClass.Export(ExportOptions pExportOptions, RequestContext pRequestContext)
   at CrystalDecisions.ReportSource.EromReportSourceBase.ExportToStream(ExportRequestContext reqContext)

**Comment by k00l3** [comment]
Please ignore I was being stupid....
